version: "2"
services:
    www:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
            - ./dump:/var/www/dump/
        links:
            - db
        networks:
            - default
    db:
        build:
            context: .
            dockerfile: Dockerfile.mysql
        ports: 
            - "3307:3306"
        environment:
            MYSQL_DATABASE: main_db
            MYSQL_USER: user
            MYSQL_PASSWORD: UserPassword
            MYSQL_ROOT_PASSWORD: RootPassword
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            # - persistent:/var/lib/mysql
            - ./secret:/secret
        networks:
            - default
volumes:
    persistent:
